config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/portfolio' =>  'pages#portfolio', as: :portfolio
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100i,300,500,700" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <script src="//code.jquery.com/jquery-latest.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="row">
        <div class="menu col-xs-8">
          <ul>
            <li><%= link_to "Welcome", root_path %></li>
            <li><%= link_to "Portfolio", portfolio_path %></li>
            <li><%= link_to "Blog", 'https://medium.com/@hervetunga', target: '_blank' %> </li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </div>
        <div class="name col-xs-4">
          <h1>Herve Tunga</h1>
        </div>
      </div>
    </div>
  </div>
  
<%= yield %>
  
</body>
    <div class="footer">
      <div class="container">
        <ul class="social_media">
          <li><a class="github" href="#">github</a></li>
          <li><a class="linkedin" href="#">linkedin</a></li>
          <li><a class="twitter" href="#">twitter</a></li> 
        </ul>
      </div>
    </div>
</html>

app/views/pages/about.html.erb
<div class="main about">
  <div class="container">
    <div class="row">
      <div class="col-md-6 thumbnail">
        <img alt="Me" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Backlit_keyboard.jpg/640px-Backlit_keyboard.jpg">
      </div>
      <div class="col-md-6">
        <h2>Hello. My name is <span class="highlight">Herve Tunga</span></h2>
        <p>I was born in 1982 in Brussels and raised in many places, mostly Belgium though, before moving to Paris at the end of my MSc.</p>
        <p>Since 2000, I've been pursuing several passions among which soft-skills training, building online communities and developing creatively.</p>
        <p>Professionally speaking, I work on developping web applications using HTML, CSS, JS, PHP, Java and, lately, Ruby on Rails.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="main contact">
  <div class="container">
    <h2>Contact me</h2>
    <div class="row">
      <div class="col-md-2">
        <a class="linkedin" href="#">linkedin</a>
      </div>
      <div class="col-md-2">
        <a class="github" href="#">github</a>
      </div>
      <div class="col-md-2">
        <a class="twitter" href="#">twitter</a>
      </div>
      <div class="col-md-2">
        <a class="facebook" href="#">facebook</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div class="main">
  <div class="banner">
    <ul>
        <li>This is a slide.</li>
        <li>This is another slide.</li>
        <li>This is a final slide.</li>
    </ul>
</div>
</div>

app/views/pages/welcome.html.erb
<div class="main home">
  <div class="jumbotron">
    <div class="container">
      <h2>
        Hello. My name is 
        <span class="highlight">Herve Tunga</span> 
        and I have creative ideas and build websites
      </h2>
      <a class="btn right" href="portfolio">View my Work</a>
    </div>
  </div>
</div>